---

- name: Simple playbook to install HTTPD package
  hosts: group1
  become: yes
  become_method: sudo
  gather_facts: yes

  tasks:
  - name: Install httpd
    yum: name=httpd state=present


  - name: Copy index.html file
    copy: src=/tmp/index.html dest=/var/www/html owner=apache mode=0644 backup=yes

  - name: Start httpd service
    service: name=httpd state=started
